admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

prueba:
    resource: "@PruebaBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
